[zh-CN]
  title = "淡淡 - 热爱生活与梦想"
  languageName = "中文"
  weight = 1
  contentdir = "content/zh-CN"

[en]
  title = "Vector - Loving life and dreams."
  languageName = "English"
  weight = 2
  contentdir = "content/en"
